# cSpell: disable
name: Build base image and RootFS
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-base
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export as root fs
        uses: docker/build-push-action@v3
        with:
          context: ./base
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=tar,dest=alpine-boxes-base.rootfs.tar

      - name: Compress root filesystem and compute checksum
        run: |
          gzip alpine-boxes-base.rootfs.tar
          sha256sum alpine-boxes-base.rootfs.tar.gz >> SHA256SUMS

      - name: Upload root fs artifact
        uses: actions/upload-artifact@v3
        with:
          name: rootfs
          path: |
            alpine-boxes-base.rootfs.tar.gz

      - name: Upload shasums artifact
        uses: actions/upload-artifact@v3
        with:
          name: shasums
          path: |
            SHA256SUMS

  build-docker:
    needs: [build-base]
    uses: ./.github/workflows/build-box.yml
    with:
      context: docker
    secrets: inherit

  build-podman:
    needs: [build-base]
    uses: ./.github/workflows/build-box.yml
    with:
      context: podman
    secrets: inherit

  release-rootfses:
    needs: [build-base, build-docker]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/v') && !github.event.release.prerelease
    steps:
      - name: Get Root File Systems
        uses: actions/download-artifact@v3

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rootfs/alpine-boxes-*.rootfs.tar.gz
            shasums/SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
