# cSpell: disable
name: Publish docker image on docker hub
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-base
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export as root fs
        uses: docker/build-push-action@v3
        with:
          context: ./base
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=tar,dest=alpine-boxes-base.tar

      - name: Compress root filesystem and compute checksum
        run: |
          gzip alpine-boxes-base.tar
          sha256sum alpine-boxes-base.tar.gz >> SHA256SUMS
      - name: Upload root fs artifact
        uses: actions/upload-artifact@v3
        with:
          name: rootfs
          path: |
            alpine-boxes-base.tar.gz
            SHA256SUMS
      - name: release
        if: contains(github.ref, 'refs/tags/v') && !github.event.release.prerelease
        uses: softprops/action-gh-release@v1
        with:
          files: |
            alpine-boxes-base.tar.gz
            SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
